bb/config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :homes
  resources :tours
  resources :flights
  resources :resaturants
  resources :guesthouses
  resources :hotels
  resources :places
  root "places#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bb/app/models/resaturant.rb
class Resaturant < ApplicationRecord
end

bb/app/controllers/resaturants_controller.rb
class ResaturantsController < ApplicationController
  http_basic_authenticate_with name: "Resturant", password: "hero1234", except: [:index, :show]
  
  before_action :set_resaturant, only: [:show, :edit, :update, :destroy]

  # GET /resaturants
  # GET /resaturants.json
  def index
    @resaturants = Resaturant.all
  end

  # GET /resaturants/1
  # GET /resaturants/1.json
  def show
  end

  # GET /resaturants/new
  def new
    @resaturant = Resaturant.new
  end

  # GET /resaturants/1/edit
  def edit
  end

  # POST /resaturants
  # POST /resaturants.json
  def create
    @resaturant = Resaturant.new(resaturant_params)

    respond_to do |format|
      if @resaturant.save
        format.html { redirect_to @resaturant, notice: 'Resaturant was successfully created.' }
        format.json { render :show, status: :created, location: @resaturant }
      else
        format.html { render :new }
        format.json { render json: @resaturant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resaturants/1
  # PATCH/PUT /resaturants/1.json
  def update
    respond_to do |format|
      if @resaturant.update(resaturant_params)
        format.html { redirect_to @resaturant, notice: 'Resaturant was successfully updated.' }
        format.json { render :show, status: :ok, location: @resaturant }
      else
        format.html { render :edit }
        format.json { render json: @resaturant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resaturants/1
  # DELETE /resaturants/1.json
  def destroy
    @resaturant.destroy
    respond_to do |format|
      format.html { redirect_to resaturants_url, notice: 'Resaturant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resaturant
      @resaturant = Resaturant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resaturant_params
      params.require(:resaturant).permit(:name, :location, :contact)
    end
end

bb/app/helpers/resaturants_helper.rb
module ResaturantsHelper
end

bb/app/views/resaturants/_form.html.erb
<%= form_for @resaturant, :html => { :class => "form-horizontal resaturant" } do |f| %>

  <% if @resaturant.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@resaturant.errors.count, "error") %> prohibited this resaturant from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @resaturant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :location, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
    <%=f.error_span(:location) %>
  </div>
  <div class="form-group">
    <%= f.label :contact, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                resaturants_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

bb/app/views/resaturants/edit.html.erb
<%- model_class = Resaturant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

bb/app/views/resaturants/index.html.erb
<%- model_class = Resaturant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:contact) %></th>
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @resaturants.each do |resaturant| %>
      <tr>
        <td><%= link_to resaturant.id, resaturant_path(resaturant) %></td>
        <td><%= resaturant.name %></td>
        <td><%= resaturant.location %></td>
        <td><%= resaturant.contact %></td>
        
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      resaturant_path(resaturant), :class => 'btn btn-default btn-xs' %>
          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_resaturant_path,
            :class => 'btn btn-primary' %>

bb/app/views/resaturants/new.html.erb
<%- model_class = Resaturant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

bb/app/views/resaturants/show.html.erb
<%- model_class = Resaturant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @resaturant.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @resaturant.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact) %>:</strong></dt>
  <dd><%= @resaturant.contact %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              resaturants_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_resaturant_path(@resaturant), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              resaturant_path(@resaturant),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>