bb/config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :homes
  resources :tours
  resources :flights
  resources :resaturants
  resources :guesthouses
  resources :hotels
  resources :places
  root "places#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bb/app/models/hotel.rb
class Hotel < ApplicationRecord
end

bb/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  http_basic_authenticate_with name: "Hotel", password: "hero1234", except: [:index, :show]
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:name, :location, :contact)
    end
end

bb/app/helpers/hotels_helper.rb
module HotelsHelper
end

bb/app/views/hotels/_form.html.erb
<%= form_for @hotel, :html => { :class => "form-horizontal hotel" } do |f| %>

  <% if @hotel.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @hotel.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :location, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
    <%=f.error_span(:location) %>
  </div>
  <div class="form-group">
    <%= f.label :contact, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                hotels_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

bb/app/views/hotels/edit.html.erb
<%- model_class = Hotel -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

bb/app/views/hotels/index.html.erb
<%- model_class = Hotel -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:contact) %></th>
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= link_to hotel.id, hotel_path(hotel) %></td>
        <td><%= hotel.name %></td>
        <td><%= hotel.location %></td>
        <td><%= hotel.contact %></td>
        
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      hotel_path(hotel), :class => 'btn btn-default btn-xs' %>
          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_hotel_path,
            :class => 'btn btn-primary' %>

bb/app/views/hotels/new.html.erb
<%- model_class = Hotel -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

bb/app/views/hotels/show.html.erb
<%- model_class = Hotel -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @hotel.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @hotel.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact) %>:</strong></dt>
  <dd><%= @hotel.contact %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              hotels_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_hotel_path(@hotel), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              hotel_path(@hotel),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>