bb/config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :homes
  resources :tours
  resources :flights
  resources :resaturants
  resources :guesthouses
  resources :hotels
  resources :places
  root "places#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bb/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bb/app/models/flight.rb
class Flight < ApplicationRecord
end

bb/app/models/guesthouse.rb
class Guesthouse < ApplicationRecord
end

bb/app/models/home.rb
class Home < ApplicationRecord
    validates :title, presence: true, length: { minimum: 5 }
    has_one_attached :image

end

bb/app/models/hotel.rb
class Hotel < ApplicationRecord
end

bb/app/models/page.rb
class Page < ApplicationRecord
end

bb/app/models/place.rb
class Place < ApplicationRecord
    validates :name, presence: true, length: { minimum: 5 }
  has_one_attached :image
end

bb/app/models/resaturant.rb
class Resaturant < ApplicationRecord
end

bb/app/models/tour.rb
class Tour < ApplicationRecord
end

bb/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:title, :image)
    end

    def article_params
      params.require(:article).permit(:title, :text, :image)
    end
end

bb/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:name, :image)
    end
end

bb/app/helpers/application_helper.rb
module ApplicationHelper
end

bb/app/helpers/flights_helper.rb
module FlightsHelper
end

bb/app/helpers/guesthouses_helper.rb
module GuesthousesHelper
end

bb/app/helpers/homes_helper.rb
module HomesHelper
end

bb/app/helpers/hotels_helper.rb
module HotelsHelper
end

bb/app/helpers/pages_helper.rb
module PagesHelper
end

bb/app/helpers/places_helper.rb
module PlacesHelper
end

bb/app/helpers/resaturants_helper.rb
module ResaturantsHelper
end

bb/app/helpers/tours_helper.rb
module ToursHelper
end

bb/app/views/layouts/_navagation_bar.html.erb
<div class="row" style="background-color: black">
<div class="container">

<div class="row">
<div class="col-md-4">
<ul class="navbar-nav mx-auto">
<li class="nav-item active">
<a class="nav-link" href="#"><h3>Travel Guide </h3> <span class="sr-only">(current)</span></a>
  
</li></ul></div>


<div class="col-md-2">
<ul class="navbar-nav mx-auto">
<li class="nav-item active">
  <a class="nav-link" href="#"> <%= link_to " Home", pages_url %>  <span class="sr-only">(current)</span></a>
</li></ul></div>

<div class="col-md-2">
<ul class="navbar-nav mx-auto">
<li class="nav-item active">
  <a class="nav-link" href="#">Documentation <span class="sr-only">(current)</span></a>
</li></ul></div>




<div class="col-md-2">
<ul class="navbar-nav mx-auto">
<li class="nav-item active">
  <a class="nav-link" href="#">About us <span class="sr-only">(current)</span></a>
</li></ul></div>

<div class="col-md-2">
<ul class="navbar-nav mx-auto">
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown08" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Other</a>
<div class="dropdown-menu" aria-labelledby="dropdown08">
  <a class="dropdown-item" href="#"><%= link_to " place", places_url %></a>
  <a class="dropdown-item" href="#"><%= link_to " hotel", hotels_url %></a>
  <a class="dropdown-item" href="#"><%= link_to " guesthouse", guesthouses_url %></a>
  <a class="dropdown-item" href="#"><%= link_to " resaturant", resaturants_url %></a>
  <a class="dropdown-item" href="#"><%= link_to " flight", flights_url %></a>
  <a class="dropdown-item" href="#"><%= link_to " tour", tours_url %></a>

</div>
</li></ul></div>

</div>
</div>
</div>
</div>

bb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travel Guide</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  
    </head>


    <style>
    .navbar {
      margin-botton: 0;
      border-radius: 0;
      background-color: rgb(20, 18, 20);
      color: #FFF;
      padding: 1% 0;
      font-size: 1.2em:
    border: 0; 
  }
    </style>
  <body background-color ="blue">
  
 
 <%= render "layouts/navagation_bar" %>
 
 
 
 
  
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<%= yield %>
  </body>
</html>

bb/app/views/layouts/home.html.erb
<!DOCTYPE html>
<body>
<h1> Welcome to Myanmar.</h1>


<img src ="/home/may/Desktop/hero/i1.jpg">
</body>
</html>